// Backend scoring rules config — mirrors src/config/scoringRules.ts
export const SCORING_RULES = {
  infrastructureControl: { 'Very High': { iaas: 5, paas: 2, saas: 1 }, High: { iaas: 5, paas: 3, saas: 1 }, Medium: { iaas: 3, paas: 4, saas: 3 }, Low: { iaas: 2, paas: 4, saas: 5 }, 'Very Low': { iaas: 1, paas: 3, saas: 5 } },
  customization: { 'Very High': { iaas: 5, paas: 4, saas: 1 }, High: { iaas: 5, paas: 4, saas: 2 }, Medium: { iaas: 3, paas: 4, saas: 3 }, Low: { iaas: 2, paas: 3, saas: 5 }, 'Very Low': { iaas: 1, paas: 2, saas: 5 } },
  scalability: { 'Very High': { iaas: 5, paas: 5, saas: 3 }, High: { iaas: 4, paas: 5, saas: 4 }, Medium: { iaas: 3, paas: 4, saas: 4 }, Low: { iaas: 3, paas: 3, saas: 4 }, 'Very Low': { iaas: 2, paas: 3, saas: 5 } },
  performance: { 'Very High': { iaas: 5, paas: 4, saas: 2 }, High: { iaas: 5, paas: 4, saas: 3 }, Medium: { iaas: 3, paas: 4, saas: 4 }, Low: { iaas: 3, paas: 3, saas: 4 }, 'Very Low': { iaas: 2, paas: 3, saas: 5 } },
  security: { 'Very High': { iaas: 5, paas: 4, saas: 2 }, High: { iaas: 5, paas: 4, saas: 3 }, Medium: { iaas: 4, paas: 4, saas: 4 }, Low: { iaas: 3, paas: 4, saas: 4 }, 'Very Low': { iaas: 3, paas: 4, saas: 5 } },
  integration: { 'Very High': { iaas: 5, paas: 4, saas: 2 }, High: { iaas: 4, paas: 5, saas: 3 }, Medium: { iaas: 3, paas: 4, saas: 4 }, Low: { iaas: 2, paas: 3, saas: 4 }, 'Very Low': { iaas: 2, paas: 3, saas: 5 } },
  technicalExpertise: { 'Very High': { iaas: 5, paas: 4, saas: 2 }, High: { iaas: 5, paas: 4, saas: 3 }, Medium: { iaas: 3, paas: 4, saas: 4 }, Low: { iaas: 2, paas: 4, saas: 5 }, 'Very Low': { iaas: 1, paas: 3, saas: 5 } },
  managementPreference: { 'Very High': { iaas: 5, paas: 3, saas: 1 }, High: { iaas: 4, paas: 3, saas: 2 }, Medium: { iaas: 3, paas: 4, saas: 3 }, Low: { iaas: 2, paas: 4, saas: 5 }, 'Very Low': { iaas: 1, paas: 4, saas: 5 } },
  maintenanceTolerance: { 'Very High': { iaas: 5, paas: 4, saas: 2 }, High: { iaas: 5, paas: 4, saas: 3 }, Medium: { iaas: 3, paas: 4, saas: 4 }, Low: { iaas: 2, paas: 4, saas: 5 }, 'Very Low': { iaas: 1, paas: 3, saas: 5 } },
  deploymentSpeed: { 'Very High': { iaas: 2, paas: 4, saas: 5 }, High: { iaas: 2, paas: 4, saas: 5 }, Medium: { iaas: 3, paas: 4, saas: 4 }, Low: { iaas: 4, paas: 3, saas: 3 }, 'Very Low': { iaas: 5, paas: 3, saas: 2 } },
  budget: { 'Very High': { iaas: 5, paas: 4, saas: 3 }, High: { iaas: 4, paas: 4, saas: 4 }, Medium: { iaas: 3, paas: 4, saas: 4 }, Low: { iaas: 2, paas: 3, saas: 5 }, 'Very Low': { iaas: 1, paas: 3, saas: 5 } },
  costSensitivity: { 'Very High': { iaas: 2, paas: 3, saas: 5 }, High: { iaas: 3, paas: 3, saas: 5 }, Medium: { iaas: 3, paas: 4, saas: 4 }, Low: { iaas: 4, paas: 4, saas: 3 }, 'Very Low': { iaas: 5, paas: 4, saas: 2 } },
  timeToMarket: { 'Very High': { iaas: 1, paas: 4, saas: 5 }, High: { iaas: 2, paas: 4, saas: 5 }, Medium: { iaas: 3, paas: 4, saas: 4 }, Low: { iaas: 4, paas: 3, saas: 3 }, 'Very Low': { iaas: 5, paas: 3, saas: 2 } },
  flexibility: { 'Very High': { iaas: 5, paas: 4, saas: 2 }, High: { iaas: 5, paas: 4, saas: 3 }, Medium: { iaas: 4, paas: 4, saas: 4 }, Low: { iaas: 3, paas: 3, saas: 4 }, 'Very Low': { iaas: 2, paas: 3, saas: 5 } },
  vendorLockInTolerance: { 'Very High': { iaas: 5, paas: 4, saas: 2 }, High: { iaas: 5, paas: 4, saas: 3 }, Medium: { iaas: 4, paas: 4, saas: 4 }, Low: { iaas: 3, paas: 3, saas: 4 }, 'Very Low': { iaas: 2, paas: 3, saas: 5 } },
};

export const CATEGORY_WEIGHTS = { technical: 0.40, operational: 0.25, financial: 0.20, business: 0.15 };
export const FACTOR_CATEGORIES = { infrastructureControl: 'technical', customization: 'technical', scalability: 'technical', performance: 'technical', security: 'technical', integration: 'technical', technicalExpertise: 'operational', managementPreference: 'operational', maintenanceTolerance: 'operational', deploymentSpeed: 'operational', budget: 'financial', costSensitivity: 'financial', timeToMarket: 'business', flexibility: 'business', vendorLockInTolerance: 'business' };
export const FACTOR_LABELS = { infrastructureControl: 'Infrastructure Control', customization: 'Customization Requirement', scalability: 'Scalability', performance: 'Performance', security: 'Security', integration: 'Integration', technicalExpertise: 'Technical Team Expertise', managementPreference: 'Infrastructure Management Preference', maintenanceTolerance: 'Maintenance Tolerance', deploymentSpeed: 'Deployment Speed', budget: 'Budget', costSensitivity: 'Cost Sensitivity', timeToMarket: 'Time to Market', flexibility: 'Flexibility', vendorLockInTolerance: 'Vendor Lock-in Tolerance' };
export const FACTOR_WEIGHTS = { infrastructureControl: 1/6, customization: 1/6, scalability: 1/6, performance: 1/6, security: 1/6, integration: 1/6, technicalExpertise: 1/4, managementPreference: 1/4, maintenanceTolerance: 1/4, deploymentSpeed: 1/4, budget: 1/2, costSensitivity: 1/2, timeToMarket: 1/3, flexibility: 1/3, vendorLockInTolerance: 1/3 };
export const CONFIDENCE_THRESHOLDS = { high: 15, moderate: 8 };
