// ============================================================
// Demo Data — Five pre-configured industry scenarios
// ============================================================
// These create requirements that the decision engine evaluates.
// The recommendation comes from the scoring engine, NOT hard-coded.
// ============================================================

import type { ScenarioInput } from '@/types';

export const DEMO_SCENARIOS: ScenarioInput[] = [
  {
    name: 'Custom E-Commerce Platform',
    organization_name: 'ShopTech Solutions',
    industry: 'E-Commerce',
    description: 'An organization wants to build a custom e-commerce platform with custom APIs, custom database, and high scalability requirements.',
    application_type: 'E-Commerce Platform',
    user_count: 50000,
    traffic_level: 'High',
    complexity: 'High',
    customization: 'High',
    infrastructure_control: 'Medium',
    scalability: 'High',
    performance: 'High',
    availability: 'High',
    security: 'High',
    integration: 'High',
    technical_expertise: 'High',
    management_preference: 'Low',
    maintenance_tolerance: 'Medium',
    deployment_speed: 'High',
    budget: 'Medium',
    cost_sensitivity: 'Medium',
    usage_pattern: 'Seasonal',
    pricing_preference: 'Pay-as-you-go',
    time_to_market: 'High',
    flexibility: 'High',
    vendor_lockin_tolerance: 'Medium',
  },
  {
    name: 'Off-the-Shelf CRM',
    organization_name: 'Global Sales Corp',
    industry: 'Sales',
    description: 'A company needs CRM software. They do not want to build, manage servers, or maintain databases. They want ready-to-use CRM software.',
    application_type: 'CRM System',
    user_count: 500,
    traffic_level: 'Low',
    complexity: 'Low',
    customization: 'Low',
    infrastructure_control: 'Very Low',
    scalability: 'Medium',
    performance: 'Medium',
    availability: 'Medium',
    security: 'Medium',
    integration: 'Medium',
    technical_expertise: 'Low',
    management_preference: 'Very Low',
    maintenance_tolerance: 'Very Low',
    deployment_speed: 'Very High',
    budget: 'Medium',
    cost_sensitivity: 'High',
    usage_pattern: 'Steady',
    pricing_preference: 'Subscription',
    time_to_market: 'Very High',
    flexibility: 'Low',
    vendor_lockin_tolerance: 'High',
  },
  {
    name: 'Custom Network Infrastructure',
    organization_name: 'Enterprise Data Systems',
    industry: 'Infrastructure',
    description: 'A large organization requires virtual machines, custom networking, firewalls, storage, and OS-level control for their data center migration.',
    application_type: 'Custom Infrastructure',
    user_count: 1000,
    traffic_level: 'Medium',
    complexity: 'Very High',
    customization: 'Very High',
    infrastructure_control: 'Very High',
    scalability: 'Medium',
    performance: 'High',
    availability: 'High',
    security: 'Very High',
    integration: 'High',
    technical_expertise: 'Very High',
    management_preference: 'Very High',
    maintenance_tolerance: 'High',
    deployment_speed: 'Low',
    budget: 'High',
    cost_sensitivity: 'Low',
    usage_pattern: 'Predictable',
    pricing_preference: 'Reserved',
    time_to_market: 'Low',
    flexibility: 'Very High',
    vendor_lockin_tolerance: 'Very High',
  },
  {
    name: 'Online Learning Platform',
    organization_name: 'EduTech Academy',
    industry: 'Education',
    description: 'An ed-tech company wants to build a highly scalable online learning platform with custom application logic but low infrastructure management.',
    application_type: 'Learning Platform',
    user_count: 20000,
    traffic_level: 'High',
    complexity: 'High',
    customization: 'High',
    infrastructure_control: 'Low',
    scalability: 'Very High',
    performance: 'High',
    availability: 'High',
    security: 'Medium',
    integration: 'High',
    technical_expertise: 'Medium',
    management_preference: 'Low',
    maintenance_tolerance: 'Low',
    deployment_speed: 'High',
    budget: 'Medium',
    cost_sensitivity: 'Medium',
    usage_pattern: 'Seasonal',
    pricing_preference: 'Pay-as-you-go',
    time_to_market: 'High',
    flexibility: 'High',
    vendor_lockin_tolerance: 'Medium',
  },
  {
    name: 'Small Business Collaboration Tool',
    organization_name: 'TinyCorp',
    industry: 'Technology',
    description: 'A small business needs collaboration software (email, document sharing, chat) without building or managing anything.',
    application_type: 'Collaboration Tool',
    user_count: 50,
    traffic_level: 'Very Low',
    complexity: 'Very Low',
    customization: 'Very Low',
    infrastructure_control: 'Very Low',
    scalability: 'Low',
    performance: 'Low',
    availability: 'Medium',
    security: 'Medium',
    integration: 'Low',
    technical_expertise: 'Very Low',
    management_preference: 'Very Low',
    maintenance_tolerance: 'Very Low',
    deployment_speed: 'Very High',
    budget: 'Low',
    cost_sensitivity: 'High',
    usage_pattern: 'Steady',
    pricing_preference: 'Subscription',
    time_to_market: 'Very High',
    flexibility: 'Low',
    vendor_lockin_tolerance: 'High',
  },
];

export const DEMO_SCENARIO_EXPECTATIONS: Record<string, string> = {
  'Custom E-Commerce Platform': 'PaaS (competitive with IaaS)',
  'Off-the-Shelf CRM': 'SaaS',
  'Custom Network Infrastructure': 'IaaS',
  'Online Learning Platform': 'PaaS',
  'Small Business Collaboration Tool': 'SaaS',
};
